### ISSUE TITLE
直辖市的县没内容,内容都跑到市区里面去了

### ISSUE THREAD

**Issue by ghost** [QingWei-Li/vue-region-picker#10]
比如:北京 -> 北京市郊县 ,然后第三级没有了

**Comment by QingWei-Li** [comment]
我找来的地区数据就是这样的

``` json
  "110100": {
    "110101": "东城区",
    "110102": "西城区",
    "110105": "朝阳区",
    "110106": "丰台区",
    "110107": "石景山区",
    "110108": "海淀区",
    "110109": "门头沟区",
    "110111": "房山区",
    "110112": "通州区",
    "110113": "顺义区",
    "110114": "昌平区",
    "110115": "大兴区",
    "110116": "怀柔区",
    "110117": "平谷区",
    "110228": "密云县",
    "110229": "延庆县"
  }
```

https://github.com/QingWei-Li/vue-region-picker/blob/master/src/china-region.json#L42-L58

**Comment by ghost** [comment]
看来是找到的数据本身就是错的了,我觉着这个可以改一下
http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201504/t20150415_712722.html

**Comment by ghost** [comment]
不光北京地区呀,好像直辖市都有这个情况

**Comment by QingWei-Li** [comment]
..........好吧 找不到好的地区数据啊，上面那个没有港澳台的数据

**Comment by azad112358** [comment]
国家统计局官网上没有港澳台的数据,说明本身就没有这些数据吧,可以用本身来代替?

**Comment by ghost** [comment]
这3个地区好像政府没有给它们划分区域代码吧?

**Comment by QingWei-Li** [comment]
不知道... 有时间我在找下吧，其实那个数据文件是独立出来的，你自己也可以更新里面的数据

**Comment by ghost** [comment]
是的,我可以修改,但是多人合作项目就不太好了

**Comment by ghost** [comment]
[台湾](https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E8%A1%8C%E6%94%BF%E5%8C%BA%E5%88%92%E4%BB%A3%E7%A0%81_%287%E5%8C%BA%29)
[香港澳门](https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E8%A1%8C%E6%94%BF%E5%8C%BA%E5%88%92%E4%BB%A3%E7%A0%81_%288%E5%8C%BA%29)

**Comment by QingWei-Li** [comment]
3.0 版使用 https://github.com/airyland/china-area-data 提供的地区数据
