### ISSUE TITLE
微信端选择'区'时的问题

### ISSUE THREAD

**Issue by libertyAlone** [QingWei-Li/vue-region-picker#17]
在微信端，当选择天津或重庆的郊县时，第三级地区没有数据

**Comment by QingWei-Li** [comment]
数据有问题，我找时间找一份靠谱的数据。

**Comment by libertyAlone** [comment]
@QingWei-Li 在PC浏览器上是有数据的，只有在微信端有问题

**Comment by QingWei-Li** [comment]
怎么可能，我刚才看了下数据，郊县底下没有值。然后我试了下 demo 也是没有值的。

**Comment by libertyAlone** [comment]
应该是版本的问题，我本地的依赖版本数据比较新，测试线上的版本数据是空的

**Comment by QingWei-Li** [comment]
3.0 版使用 https://github.com/airyland/china-area-data 提供的地区数据
