### ISSUE TITLE
可以输出地区的 id 吗?

### ISSUE THREAD

**Issue by berryliu** [QingWei-Li/vue-region-picker#18]
可以配置使得 get 得到 id 而不是名称吗？

**Comment by QingWei-Li** [comment]
目前只支持获取地区名，或者数组 `[id, 地区名]`。所以如果是用在提交表单上，提交前自己手动提取 id 就好了；如果是需要个只获取 id 的变量，自己写个 computed 去处理。

**Comment by berryliu** [comment]
对不起，没注意到 completed 选项，谢谢啦！
