### ISSUE TITLE
如何使用自己 json 文件？

### ISSUE THREAD

**Issue by iblh** [QingWei-Li/vue-region-picker#28]

**Comment by QingWei-Li** [comment]
region 传入你的 json 对象就就好了

**Comment by iblh** [comment]
对于JSON 的名称和格式是否有限定？或者能否自定义？

**Comment by QingWei-Li** [comment]
有，必须按照 https://github.com/airyland/china-area-data/blob/master/index.js 这个

**Comment by iblh** [comment]
名称是指文件内部数据所对应的key

**Comment by QingWei-Li** [comment]
数据只要和 https://github.com/QingWei-Li/vue-region-picker/issues/28#issuecomment-271804267 提到的格式一致就可以，否则需要自己改代码
