### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by QingWei-Li** [QingWei-Li/vue-region-picker#4]
- [x] [refactor] 移除 init 直接通过 province/city/district 设置值，并支持 **双向绑定**
- [x] [feature] 支持二级联动 province / city #2 
- [ ] [feature] 自定义地区数据生成工具，可以选择指定的省市区，或者自己填数据，生成 json 文件 (辅助工具，慢慢做）

**Comment by libertyAlone** [comment]
请问如何根据接口返回的省市区三个字段进行地址回填

**Comment by QingWei-Li** [comment]
hi, @libertyAlone 
2.0 就双向绑定了，现在的版本只能初始化数据
